/*
 * Offline PDF Reader with Local LLM - Summary Panel
 * Copyright (c) 2024-2026 Tereza Gorgolova
 * All rights reserved.
 */

import { useState } from 'react';

export default function SummaryPanel({ summary, summaryError, onExport, isLoading, onRetry }) {
  const [isExpanded, setIsExpanded] = useState(true);

  if (isLoading) {
    return (
      <div className="summary-panel">
        <div className="summary-header">
          <h3>Generating Summary...</h3>
        </div>
        <div className="summary-loading">
          <div className="spinner"></div>
          <p>The AI is analyzing your document.</p>
          <p className="loading-hint">This may take 30-60 seconds for longer documents.</p>
        </div>
      </div>
    );
  }

  if (summaryError) {
    return (
      <div className="summary-panel">
        <div className="summary-header">
          <h3>Summary</h3>
        </div>
        <div className="summary-error">
          <div className="error-icon">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="12" />
              <line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
          </div>
          <h4>Could not generate summary</h4>
          <p className="error-message">{summaryError}</p>
          {onRetry && (
            <button onClick={onRetry} className="retry-btn">
              Try Again
            </button>
          )}
        </div>
      </div>
    );
  }

  if (!summary) {
    return (
      <div className="summary-panel">
        <div className="summary-header">
          <h3>Summary</h3>
        </div>
        <div className="empty-state">
          <p>Upload a PDF to see an AI-generated summary here.</p>
        </div>
      </div>
    );
  }

  const paragraphs = formatSummaryParagraphs(summary);

  return (
    <div className="summary-panel">
      <div className="summary-header">
        <div className="summary-title">
          <h3>Document Summary</h3>
          <button
            className="toggle-btn"
            onClick={() => setIsExpanded(!isExpanded)}
            aria-label={isExpanded ? 'Collapse summary' : 'Expand summary'}
          >
            {isExpanded ? '−' : '+'}
          </button>
        </div>
        <div className="export-buttons">
          <button onClick={() => onExport('txt')} className="export-btn">
            Export .txt
          </button>
          <button onClick={() => onExport('md')} className="export-btn">
            Export .md
          </button>
          <button onClick={() => onExport('csv')} className="export-btn">
            Export Tables
          </button>
        </div>
      </div>

      {isExpanded && (
        <div className="summary-content">
          <div className="summary-section">
            <h4>AI-Generated Summary</h4>
            <div className="summary-text">
              {paragraphs.map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
              ))}
            </div>
          </div>

          <div className="summary-meta">
            <span className="meta-item">
              Generated by local LLM
            </span>
            <span className="meta-separator">•</span>
            <span className="meta-item">
              {paragraphs.length} paragraph{paragraphs.length !== 1 ? 's' : ''}
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

function formatSummaryParagraphs(summary) {
  if (!summary || typeof summary !== 'string') {
    return ['No summary available.'];
  }

  const lines = summary.split('\n');
  const paragraphs = [];
  let currentParagraph = '';

  for (const line of lines) {
    const trimmedLine = line.trim();

    if (!trimmedLine) {
      if (currentParagraph) {
        paragraphs.push(currentParagraph.trim());
        currentParagraph = '';
      }
      continue;
    }

    if (currentParagraph) {
      currentParagraph += ' ' + trimmedLine;
    } else {
      currentParagraph = trimmedLine;
    }
  }

  if (currentParagraph) {
    paragraphs.push(currentParagraph.trim());
  }

  const cleanedParagraphs = paragraphs
    .filter(p => p.length > 20)
    .filter((p, index, arr) => {
      const normalized = p.toLowerCase().replace(/[^a-z0-9]/g, '');
      return arr.findIndex(other =>
        other.toLowerCase().replace(/[^a-z0-9]/g, '') === normalized
      ) === index;
    });

  if (cleanedParagraphs.length === 0) {
    return [summary.trim()];
  }

  return cleanedParagraphs;
}
